# Exercise : Tensor Manipulation

In [ ]:
import tensorflow as tf

### Creating a scalar tensor

In [ ]:
tens0=tf.constant(5)
print(tens0)

tf.Tensor(5, shape=(), dtype=int32)


### Creating a 1-d tensor

In [ ]:
tens2=tf.constant([5,8,-1,0])
print(tens2)

tf.Tensor([ 5  8 -1  0], shape=(4,), dtype=int32)


### Creating a 2-d tensor

In [ ]:
tens3=tf.constant([[5,8,-1,0],[4,3,2,1]])
print(tens3)

tf.Tensor(
[[ 5  8 -1  0]
 [ 4  3  2  1]], shape=(2, 4), dtype=int32)


### Creating a 3-d tensor

In [ ]:
tens5=tf.constant([     [[1,2,3],[4,5,6]]   ,    [[7,8,9],[10,11,12]]   ])
tens5

In [ ]:
import numpy as np
arr4=np.array( [[1,-1,0], [6,7,8], [2,3,6]] )
arr4[1,1]=100
print(arr4)

[[  1  -1   0]
 [  6 100   8]
 [  2   3   6]]


In [ ]:
tens4=tf.constant( [[1,-1,0], [6,7,8], [2,3,6]] )
print(tens4)
print(tens4[2,1]) # slicing the element
print(np.array(tens4[2,1])) # converting tensor into an array
print(np.array(tens4))
print(tens4.numpy())# converting tensor into an array - method 2


### Creating a 4-d tensor

In [ ]:
tens6=tf.constant(   [ [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]], [[[21,22,23],[24,25,26]],[[27,28,29],[30,31,32]]],[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]] ])
tens6

#### Shape, Rank and Axis

In [ ]:
tens4

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1, -1,  0],
       [ 6,  7,  8],
       [ 2,  3,  6]], dtype=int32)>

In [ ]:
tens4.shape

TensorShape([3, 3])

In [ ]:
print("Rank of tens4 is ",tf.rank(tens4).numpy())

Rank of tens4 is  2


In [ ]:
print(tens5.shape)
print("Rank of tens6 is ",tf.rank(tens5).numpy())

(2, 2, 3)
Rank of tens6 is  3


In [ ]:
print(tens6.shape)
print("Rank of tens6 is ",tf.rank(tens6).numpy())

(3, 2, 2, 3)
Rank of tens6 is  4


### Operations on Tensors

In [ ]:
A=tf.constant( [[1,-1,0], [6,7,8], [2,3,6]] )
B=tf.constant( [[0,1,2], [2,4,1], [1,2,3]] )
print(A)
print(B)

In [ ]:
A+B

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  0,  2],
       [ 8, 11,  9],
       [ 3,  5,  9]], dtype=int32)>

In [ ]:
A-B

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1, -2, -2],
       [ 4,  3,  7],
       [ 1,  1,  3]], dtype=int32)>

In [ ]:
A*B

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 0, -1,  0],
       [12, 28,  8],
       [ 2,  6, 18]], dtype=int32)>

In [ ]:
tf.matmul(A,B)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[-2, -3,  1],
       [22, 50, 43],
       [12, 26, 25]], dtype=int32)>

In [ ]:
A@B

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[-2, -3,  1],
       [22, 50, 43],
       [12, 26, 25]], dtype=int32)>

### Broadcasting of tensors

### Example 1:

In [ ]:
tens1=tf.constant(5)
tens2=tens4
print(tens2)



tf.Tensor(
[[ 1 -1  0]
 [ 6  7  8]
 [ 2  3  6]], shape=(3, 3), dtype=int32)


In [ ]:
print(tens1)

tf.Tensor(5, shape=(), dtype=int32)


In [ ]:
tens1+tens2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 6,  4,  5],
       [11, 12, 13],
       [ 7,  8, 11]], dtype=int32)>

### Example 2:

In [ ]:
t1=tf.constant([[1, 2, 3]])
t1

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]], dtype=int32)>

In [ ]:
t2=tf.constant([[4, 5, 6]])
t2

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[4, 5, 6]], dtype=int32)>

In [ ]:
t1+t2

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[5, 7, 9]], dtype=int32)>

In [ ]:
t3=tf.constant( [[1, 2, 3]])
t4=tf.constant( [[4],[5],[6]])

### Example 3: Broadcasting with same rank and different shapes

In [ ]:
t3=tf.constant( [[1, 2, 3]])
t4=tf.constant( [[4],[5],[6]])

In [ ]:
t3

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]], dtype=int32)>

In [ ]:
t4

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[4],
       [5],
       [6]], dtype=int32)>

In [ ]:
t3+t4

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]], dtype=int32)>

### Example 4

In [ ]:
tens5=tf.constant([     [[1,2,3,4]]   ,    [[7,8,9,0]], [[0,1,2,3]],    ])
tens5

<tf.Tensor: shape=(3, 1, 4), dtype=int32, numpy=
array([[[1, 2, 3, 4]],

       [[7, 8, 9, 0]],

       [[0, 1, 2, 3]]], dtype=int32)>

In [ ]:
tens6=tf.constant([         [[7],[8],[9],[0],[6]]    ])
tens5

<tf.Tensor: shape=(3, 1, 4), dtype=int32, numpy=
array([[[1, 2, 3, 4]],

       [[7, 8, 9, 0]],

       [[0, 1, 2, 3]]], dtype=int32)>

In [ ]:
tens5+tens6

### Tensorflow Functions

#### reduce_ max,reduce_min,reduce_mean, reduce_sum,reduce_prod

In [ ]:
tensor=tf.constant( [[1,-1,0,3], [6,7,18,5], [2,3,6,-3]] )
tensor

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1, -1,  0,  3],
       [ 6,  7, 18,  5],
       [ 2,  3,  6, -3]], dtype=int32)>

In [ ]:
tf.reduce_max(tensor).numpy()

18

In [ ]:
tf.reduce_max(tensor,0).numpy() # column wise max

array([ 6,  7, 18,  5], dtype=int32)

In [ ]:
tf.reduce_max(tensor,1).numpy()

array([ 3, 18,  6], dtype=int32)

#### argmax/argmin



In [ ]:
tensor=tf.constant( [[8,-1,0,13], [6,7,18,5], [12,3,6,-3]] )

In [ ]:
tf.argmax(tensor,0).numpy()

array([2, 1, 1, 0])

In [ ]:
tf.argmax(tensor,1).numpy()

array([3, 2, 0])

In [ ]:
tf.argmin(tensor,0).numpy()

array([1, 0, 0, 2])

#### Softmax

In [ ]:
tens1=tf.constant([5.,8.,-1.,0.])
tens1

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 5.,  8., -1.,  0.], dtype=float32)>

In [ ]:
sfmx=tf.nn.softmax(tens1)
sfmx.numpy()

array([4.74051535e-02, 9.52157974e-01, 1.17505624e-04, 3.19413404e-04],
      dtype=float32)

In [ ]:
print(np.exp(5.0))
print(np.exp(8.0))
print(np.exp(-1.0))
print(np.exp(0.0))
total=np.exp(5.0)+np.exp(8.0)+np.exp(-1.0)+np.exp(0.0)



148.4131591025766
2980.9579870417283
0.36787944117144233
1.0


In [ ]:
print(np.exp(5.0)/total)
print(np.exp(8.0)/total)
print(np.exp(-1.0)/total)
print(np.exp(0.0)/total)

0.04740515191131973
0.9521579290641329
0.00011750562348538316
0.00031941340106206745


#### Ragged Tensor

In [ ]:
data= [  [8,3,5], [6,7,18,5], [12,3,6,0,-1],[1,2,3]] 
rgd_array=tf.ragged.constant(data)
rgd_array

<tf.RaggedTensor [[8, 3, 5], [6, 7, 18, 5], [12, 3, 6, 0, -1], [1, 2, 3]]>

#### Sparse Tensor

In [ ]:
sprtensor =tf.sparse.SparseTensor(indices=[[1,2],[3,1],[4,4]],values=[16,18,10],dense_shape=[5,6])
sprtensor

SparseTensor(indices=tf.Tensor(
[[1 2]
 [3 1]
 [4 4]], shape=(3, 2), dtype=int64), values=tf.Tensor([16 18 10], shape=(3,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))

#### Displaying the Dense Tensor

In [ ]:
dentensor=tf.sparse.to_dense(sprtensor)
dentensor

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  0, 16,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0, 18,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 10,  0]], dtype=int32)>

#### Getting Sparse from Dense

In [ ]:
tf.sparse.from_dense(dentensor)

SparseTensor(indices=tf.Tensor(
[[1 2]
 [3 1]
 [4 4]], shape=(3, 2), dtype=int64), values=tf.Tensor([16 18 10], shape=(3,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))