# Exercise : Constraints

In [ ]:
from google.colab import files
upload=files.upload()

Saving delivery-time.csv to delivery-time.csv


In [ ]:
import io
import pandas as pd
df=pd.read_csv(io.BytesIO(upload['delivery-time.csv']))
df.head()
X=df.iloc[:,1:3]
y=df.iloc[:,0]

# Unconstrained

In [ ]:
from keras import models,layers
model=models.Sequential()
model.add(layers.Dense(4,input_dim=2))
model.compile(loss='mse')
model.fit(X,y,epochs=10,verbose=0)
model.get_weights()

[array([[ 0.962755  , -0.04816267,  0.60737836,  0.29923853],
        [-0.7566293 ,  0.48503706,  0.12725769, -0.01584307]],
       dtype=float32),
 array([-0.01727506,  0.01683282, -0.01724097, -0.01712953], dtype=float32)]

In [ ]:
model.get_weights()

[array([[ 0.962755  , -0.04816267,  0.60737836,  0.29923853],
        [-0.7566293 ,  0.48503706,  0.12725769, -0.01584307]],
       dtype=float32),
 array([-0.01727506,  0.01683282, -0.01724097, -0.01712953], dtype=float32)]

# Non Negativity Constraint

In [ ]:
from keras.constraints import NonNeg
model=models.Sequential()
model.add(layers.Dense(4,input_dim=2,kernel_constraint=NonNeg(),bias_constraint=NonNeg()))
model.compile(loss='mse')
model.fit(X,y,epochs=10,verbose=0)
model.get_weights()

[array([[ 0.75825644,  0.699994  ,  0.00382448,  0.00262713],
        [-0.        ,  0.4489392 ,  0.00412897,  0.00285896]],
       dtype=float32),
 array([-0.        , -0.        ,  0.00727173,  0.00600418], dtype=float32)]

# UnitNorm Constraint

In [ ]:
from keras.constraints import UnitNorm
model=models.Sequential()
model.add(layers.Dense(4,input_dim=2,kernel_constraint=UnitNorm()))
model.compile(loss='mse')
model.fit(X,y,epochs=10,verbose=0)
model.get_weights()

[array([[-0.8142406 ,  0.96815366, -0.5326601 , -0.27565104],
        [-0.58052737,  0.25035608, -0.8463291 ,  0.9612576 ]],
       dtype=float32),
 array([ 0.01798246, -0.01798182,  0.01787408,  0.01703612], dtype=float32)]

In [ ]:
import numpy as np
wgts=model.get_weights()
k1=wgts[0]
k1.shape
for i in range(4):
  print(np.sqrt(sum(k1[:,i]*k1[:,i])))

0.9999998658895403
0.9999998249113407
0.9999998807907033
0.9999998062848857


# MaxNorm Constraint

In [ ]:
from keras.constraints import MaxNorm
model=models.Sequential()
model.add(layers.Dense(4,input_dim=2,kernel_constraint=MaxNorm(0.3)))
model.compile(loss='mse')
model.fit(X,y,epochs=10,verbose=0)
wgts=model.get_weights()
k1=wgts[0]
k1.shape
for i in range(4):
  print(np.sqrt(sum(k1[:,i]*k1[:,i])))

0.28268299681079034
0.28304879817788364
0.2943669175650173
0.26903507702255947


# MinMaxNorm Constraint

In [ ]:
from keras.constraints import MinMaxNorm
model=models.Sequential()
model.add(layers.Dense(4,input_dim=2,kernel_constraint=MinMaxNorm(min_value=0.2,max_value=0.7)))
model.compile(loss='mse')
model.fit(X,y,epochs=10,verbose=0)
wgts=model.get_weights()
k1=wgts[0]
k1.shape
for i in range(4):
  print(np.sqrt(sum(k1[:,i]*k1[:,i])))

0.6986070546602706
0.19999989531931522
0.6836952461098883
0.6999998152255769


# L1 Regularizer

In [ ]:
from keras import regularizers
model=models.Sequential()
model.add(layers.Dense(4,input_dim=2,kernel_regularizer=regularizers.l1(0.01)))
model.compile(loss='mse')
model.fit(X,y,epochs=10,verbose=0)
wgts=model.get_weights()
k1=wgts[0]
k1.shape
for i in range(4):
  print(np.sqrt(sum(k1[:,i]*k1[:,i])))

0.5226684496899824
0.8194974665046943
1.1121635581920677
0.9969673066168979


# L2 Regularizers

In [ ]:
from keras import regularizers
model=models.Sequential()
model.add(layers.Dense(4,input_dim=2,kernel_regularizer=regularizers.l2(0.01)))
model.compile(loss='mse')
model.fit(X,y,epochs=10,verbose=0)
wgts=model.get_weights()
k1=wgts[0]
k1.shape
for i in range(4):
  print(np.sqrt(sum(k1[:,i]*k1[:,i])))

0.4683255081563097
0.39077182513794967
1.0970531992692172
1.2214788550827667
